### ISSUE TITLE
weapons arn't loading in

### ISSUE THREAD

**Issue by BadBoyDragon** [Thomasims/TeardownUMF#10]
![20210117134136_1](https://user-images.githubusercontent.com/77557315/104828024-281b3d80-58b9-11eb-937f-fb78e68e9665.jpg)
![20210117134147_1](https://user-images.githubusercontent.com/77557315/104828027-2ea9b500-58b9-11eb-90ed-4c34951a94b8.jpg)

 I've done the correct installation and its still not loading in my weapon on any map how do i fix this

**Comment by TeardownFan** [comment]
I have the same problem but it's with running the mod loader instead

**Comment by Thomasims** [comment]
I don't have any information about "your weapon" nor about the actual state of the installation of UMF, I can't give you any help without more info.

**Comment by SimonPlayz** [comment]
@Thomasims thanks that you helped me, the other game file i had was a fake game, so i downloaded the real one, now it works, thanks
