### ISSUE TITLE
how tf do you fix the error

### ISSUE THREAD

**Issue by TeardownFan** [Thomasims/TeardownUMF#13]
this is the **LAST TIME** i am asking,how do you, no one here, not even the tutorials tell me how to fix actually. How do you even do it

**Comment by Thomasims** [comment]
You have given no information about this "error", how are we meant to help you? All you do is complain about it not working vaguely and completely ignore existing resources like the [common issues page](https://github.com/Thomasims/TeardownUMF/wiki/Common-Issues) and the [installation guide](https://github.com/Thomasims/TeardownUMF-Examples/wiki/Installation-Guide) that have precise information on how to install UMF.

It might be slightly confusing without instructions but there is a guide with *pictures* showing you what you should see and you still manage to misunderstand. I'm done with this, if you have an actual error and you detail it I'll look at it but I'm tired of trying to make you understand what's already written down.

**Comment by TeardownFan** [comment]
I DID IT, IT FINALLY WORKED

**Comment by TeardownFan** [comment]
BRUH I GET A BLACK SCREEN EVERYTIME I OPEN TEARDOWN wtf


edit : I think i have the latest version i think (or not)
