### ISSUE TITLE
why tho

### ISSUE THREAD

**Issue by arceuss** [Thomasims/TeardownUMF#14]
![image](https://user-images.githubusercontent.com/28229451/106398202-ba9a0180-63ce-11eb-8efc-65a0c3565a84.png)

**Comment by arceuss** [comment]
ok and after this it tells me im on the wrong version despite me using experimental

**Comment by arceuss** [comment]
![image](https://user-images.githubusercontent.com/28229451/106398359-925ed280-63cf-11eb-8e8a-d9f9a36ccf4a.png)
???

**Comment by Thomasims** [comment]
You placed the batch file in the wrong folder. It has to be next to teardown.exe.

**Comment by arceuss** [comment]
its in the same folder as teardown.exe
i was showing that menu.lua exists
![image](https://user-images.githubusercontent.com/28229451/106398689-97248600-63d1-11eb-994a-8e1383fd6491.png)

**Comment by arceuss** [comment]
reinstalled on my f drive
same thing

**Comment by arceuss** [comment]
nvm i just did all the commands myself
it works now
