### ISSUE TITLE
TeardownUMF needs an update

### ISSUE THREAD

**Issue by foxyplayzYT** [Thomasims/TeardownUMF#17]
hello. on 5th February there was an update to 0.5.5 and TeardownUMF is running on the 
0.5.2 version. perhaps you can update it to 0.5.5?

![Screenshot_252](https://user-images.githubusercontent.com/71534108/107296032-44a23400-6a79-11eb-86e1-c7fd361ba28a.png)

**Comment by Thomasims** [comment]
Hi, as far as I know the latest release of UMF (0.5.2) is still compatible with Teardown 0.5.5.

I'm working towards the 0.6 update at the moment and was expecting to push a final release for 0.5.x before 0.6 gets on the experimental branch on steam, I suppose I could do that release now since I don't expect any more changes before then.

**Comment by foxyplayzYT** [comment]
okay, but when I went in-game it showed mods everything but nothing worked. only maps no moded weapons etc...

**Comment by foxyplayzYT** [comment]
cloud it be the mods have to be updated not umf?

**Comment by foxyplayzYT** [comment]
hello, idk what needs to be updated rn bec i don't have any weapons even a physic gun and I don't have fly what I had. do you know how to fix it?

**Comment by foxyplayzYT** [comment]
i have reinstalled every mod still doesn't work

**Comment by foxyplayzYT** [comment]
ill gonna roll the update back to 0.5.2 until stuff is sorted/fixed 


btw thx for the update and I think its  teardown side 

Edit: they locked it so i cant put older versions

**Comment by Thomasims** [comment]
When your game updates you need to re-run `hook_modloader.bat` since some files will be overwritten by the update.
Apart from that, versions in 0.5.x are generally compatible with each other, just bug fixes here and there and adding features as the API evolves.

**Comment by foxyplayzYT** [comment]
OMG THANK YOU so much it fixed it completely forgot to reopen hook_modloader.bat thank you so much!!
