### ISSUE TITLE
Can not select mods

### ISSUE THREAD

**Issue by xShawnDx** [Thomasims/TeardownUMF#18]
2/12/21- Installed UMF followed the instructions w/ no issues, mods loaded into folder, game starts up, enabled mods. They show up as a selection during game play ie: "1,2,3" for weapons selection, but they will not select when choosing the corresponding number for the mod/weapon?

**Comment by xShawnDx** [comment]
Updated: The scroll on the mouse allowed me to select the weapon mods... newb moment I guess

**Comment by Thomasims** [comment]
Sorry for the late response, but yes you're right you have to use the scroll-wheel to select custom tools.
This is intentionally done to keep the official number -> tool mapping that the game has.
