### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Piesv13** [Thomasims/TeardownUMF#19]
So whenever I try to open teardown after installing UMF and running the loader it always says something data lua  attempt to call a nil value anybody can help with this? Also whenever i want to play teardown again i need to reinstall it.

**Comment by Thomasims** [comment]
There's not enough info here to begin analyzing the problem.
- What is the exact error text?
- Did you follow the installation instructions correctly?

**Comment by berwil-1** [comment]
The most common reason for this is that the umf folder could not be found, make sure that you have extracted and moved the folder called specifically "umf" to the SteamLibrary/steamapps/common/Teardown/mods folder.

**Comment by Piesv13** [comment]
So I do not know why but i had to delete the original mod folder and then replace it with the one that was in the umf folder im not sure if i miss understood the installation guide sorry about the issue this was entirely my bad. (It works now.)
