### ISSUE TITLE
hello i have problem whit modded guns

### ISSUE THREAD

**Issue by foxyplayzYT** [Thomasims/TeardownUMF#20]
so basically i downloaded umf and mods and i opened the hook_modloader and when i went in-game uhf example mods worked but not any other guns did i do something wrong or something?

**Comment by foxyplayzYT** [comment]
this what i see when i enter game 
![Screenshot_1](https://user-images.githubusercontent.com/71534108/109685919-6c714d00-7b8a-11eb-99f9-11268dd205b5.png)
![Screenshot_2](https://user-images.githubusercontent.com/71534108/109685923-6e3b1080-7b8a-11eb-96a6-1686a25ffb73.png)

**Comment by Thomasims** [comment]
Those are tools that do not use UMF anymore. update to 0.6.1 on the experimental branch of the game to play with them.
