### ISSUE TITLE
Modded weapons does not load in the gui

### ISSUE THREAD

**Issue by HTMLDevelopment** [Thomasims/TeardownUMF#23]
I cannot switch to the modded weapons, and they are also not choosable, could you please fix it? Is this the same issue you've said before? Thank you

**Comment by Thomasims** [comment]
It's working fine for me, what are you trying exactly? Modded weapons are part of the base game now so this is most likely not related to UMF.

**Comment by HTMLDevelopment** [comment]
it's because i've downloaded a time control mod to use it with the game, and another "creative mode" mod, but they only work with umf, so i have downloaded umf (and i also have steam workshop mods loaded in the game). But since i have installed umf the modded weapons doesn't appear on the bar.
obs: modded weapons i mean tools from the workshop

**Comment by HTMLDevelopment** [comment]
specifically the tools doesn't appear, anything else from the workshop does work. Sorry for making this a bit confusing

**Comment by Thomasims** [comment]
Mods "requiring" UMF to be installed are no longer compatible with the latest version of the game. UMF has moved to being a dependency modders have to include into their mod so it should be of no concern to users.
Do not use UMF 0.5 on Teardown 0.6+

**Comment by HTMLDevelopment** [comment]
Ok. Thank you
