### ISSUE TITLE
Outdated Guide

### ISSUE THREAD

**Issue by AptemCat** [Thomasims/TeardownUMF#26]
The guide at [TeardownUMF-Examples](https://github.com/Thomasims/TeardownUMF-Examples/wiki/Installation-Guide) is outdated, because the source code in this repo looks nothing like in the guide. What should I do if I want to install a mod, requiring UMF like [this one](https://teardownmods.com/index.php?/file/911-gravity-gun/)?(Also it links to the previously mentioned guide)

**Comment by Thomasims** [comment]
That is indeed an outdated guide, on an outdated and archived repository.
Mods still requiring the user to install UMF themselves are outdated and no longer compatible with the game.

**Comment by AptemCat** [comment]
ok, thanks
