### ISSUE TITLE
Clarification on wiki page for setup

### ISSUE THREAD

**Issue by Catalyzzt** [Thomasims/TeardownUMF#29]
I ran across this issue while I was setting up UMF and figured you might want to know about it, as it seems like it would be rather common. 

Essentially, when generating an XML, you have to create a new "mod" to use the editor. I simply dragged a copy of my vox file into that new project, which is the logical approach for most users. Unfortunately, that generates a generic filepath depending on where you open the vox (namely `MOD/model.vox`). This does not reflect common practice of nesting model files in `MOD/vox/model.vox`. I would suggest adding a note below the section on generating the prefab, for example:
_Make sure all references to your vox file are accurate in the XML!_
This seems easy enough to fix with a note, but is frustrating to a new user like me. 

Ultimately, the problem is that no error is thrown, _unlike_ vanilla tool loading, which will notify users if the vox path is incorrect. I might also suggest catching errors related to a failed model load.

Cheers,
Catalyzzt

**Comment by Thomasims** [comment]
I'll add an error message if some of the shapes are detected as missing, I'm working on a fairly large update to the internals of the tool system ATM so it won't be on here for a bit.
