### ISSUE TITLE
NO

### ISSUE THREAD

**Issue by teardownoof** [Thomasims/TeardownUMF#7]
it´s don´t paching the game it opens and closes

**Comment by teardownoof** [comment]
please answer

**Comment by Thomasims** [comment]
Make sure you're installing it in the right folder and running the right version of the game.

**Comment by teardownoof** [comment]
yes but i have a cracked version

**Comment by teardownoof** [comment]
YES but i have a cracked version

**Comment by Thomasims** [comment]
Sorry, we don't provide support for cracked versions.

**Comment by teardownoof** [comment]
ok
