### ISSUE TITLE
Mod Menu is blank after patching

### ISSUE THREAD

**Issue by SorceressLyra** [Thomasims/TeardownUMF#8]
After patching the game with the latest release of `hook_modloader.bat` the main menu Mod menu is inaccessible and requires a restart of the game to get out of.

![image](https://user-images.githubusercontent.com/20424962/104314308-87ec9f80-54d9-11eb-924e-732a870d5b89.png)

**Comment by Thomasims** [comment]
I can't reproduce this issue using the latest version of the game and UMF. Verfiy your game files and make sure you're using the correct version.

**Comment by SorceressLyra** [comment]
It seemed to fix the issue by moving to the experimental branch on steam, however, the main branch is still non functional.

I have attempted full reinstalls and verification of the game files.
