### ISSUE TITLE
I keep getting this error when i open the hook modloader

### ISSUE THREAD

**Issue by TeardownFan** [Thomasims/TeardownUMF#9]
![Screenshot_1](https://user-images.githubusercontent.com/77467605/104664328-b622d880-56ad-11eb-88b7-a25dcaad0df3.jpg)
How can I fix this?

**Comment by TeardownFan** [comment]
@Thomasims how can  you help me?

**Comment by Thomasims** [comment]
The error is pretty clear, make sure your game is up to date on steam and retry.

**Comment by TeardownFan** [comment]
Thank you, but i do not know how.

**Comment by TeardownFan** [comment]
And also i play on 0.5.2, not 0.5.0. You better fix this.

**Comment by Thomasims** [comment]
The error says 0.5.x not 0.5.0. "x" in versions is widely understood to stand for "any"

**Comment by TeardownFan** [comment]
Or i might just play in 0.4.6
